#!/bin/bash

usage() {
    echo "  -H  Critical space threshold"
    echo "  -M  Lower space threshold"
    echo "  -L  Low space threshold"
    echo "  -h  Critical space colour"
    echo "  -m  Lower space colour"
    echo "  -l  Low space colour"
    echo "  -L  Test location"
}

while getopts ":H:M:L:h:m:l:i:L:" o; do
    case "${o}" in
        H)  high=${OPTARG};;
        M)  med=${OPTARG};;
        L)  low=${OPTARG};;
        h)  Col_H=${OPTARG};;
        m)  Col_M=${OPTARG};;
        l)  Col_L=${OPTARG};;
        L)  loc=${OPTARG};;
        *)  usage
            exit 1;;
    esac
done

df "${loc:-/home}" |
    awk -v High="${high:-5}" -v Med="${med:-20}" \
    -v Low="${low:-50}" -v Col_H="${Col_H:-#FF0000}" -v Col_M="${Col_M:-#FFFF00}" \
    -v Col_L="${Col_L:-#00FF00}" \
    'NR==2{
        lvl=$4/1024^2
        printf " %.1f GB\n",lvl
        printf " %.1f GB\n",lvl
        if(lvl <= High){
            print Col_H
        }else if(lvl <= Med){
            print Col_M
        }else if(lvl <= Low){
            print Col_L
        }else{
            print "#FFFFFF"
        }
    }'