#!/bin/bash

usage() {
    echo "  -H  High memory threshold"
    echo "  -M  Medium memory threshold"
    echo "  -L  Low memory threshold"
    echo "  -h  High memory colour"
    echo "  -m  Medium memory colour"
    echo "  -l  Low memory colour"
}

while getopts ":H:M:L:h:m:l:i:" o; do
    case "${o}" in
        H)  high=${OPTARG};;
        M)  med=${OPTARG};;
        L)  low=${OPTARG};;
        h)  Col_H=${OPTARG};;
        m)  Col_M=${OPTARG};;
        l)  Col_L=${OPTARG};;
        *)  usage
            exit 1;;
    esac
done

cd ${0%/*}

case "$BLOCK_BUTTON" in
    1|3) touch mem_type
        if [ "$(< mem_type)" == "1" ]; then 
            echo 0 > mem_type
        else
            echo 1 > mem_type
        fi;;
esac

if [ -f "mem_type" ] && [ "$(< mem_type)" == "1" ]; then
    free -h --si |
    awk '/Mem/{
        printf " %s/%s\n",$3,$2
    }'
else
    free |
    awk '/Mem/{
        printf " %.0f%%\n",$3/$2*100
    }'
fi