#!/bin/bash
blockdate=$(date '+%d-%m-%Y %H:%M:%S')

case "$BLOCK_BUTTON" in
    1|2|3) date=$(date '+%A, %d. %B')
export TERM=xterm
cal --color=always \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -hide-scrollbar \
        -bw 2 \
        -m -3 \
        -lines 10 \
        -theme-str '#window {anchor:southeast; location: northwest;}' \
        -eh 1 \
        -width -25 \
        -no-custom \
        -p "$date" > /dev/null 
    esac
echo $blockdate
date '+%H:%M:%S'
